### ISSUE TITLE
ipl\Sql: support Common Table Expressions (CTE)

### ISSUE THREAD

**Issue by Thomas-Gelf** [Icinga/ipl#13]
In the past it was next to impossible for us to support CTEs. They are available in PostgreSQL since quite some time, but now they are also in MariaDB 10.2.1 (well, 10.2.2 when you ask for recursive ones) and in MySQL 8. As this new library should be supported for a longer time period, we should have CTE support available from day 1.

Thanks,
Thomas

**Comment by Al2Klimov** [comment]
Again, the difference between RDBMSes and them and ANSI SQL makes me sick (and the doc...). I made all four statement types support WITH – if someone misuses this naively and their RDBMS complains – they'll have to refactor their code.
