### ISSUE TITLE
Clearly define (and document) where we shall support expressions and subqueries

### ISSUE THREAD

**Issue by Al2Klimov** [Icinga/ipl#24]
While [correcting](https://github.com/Icinga/ipl/pull/5#pullrequestreview-97528396) #5 I just blindly used `$value instanceof ExpressionInterface || $value instanceof Select` – but this should be more dispositive.

Please untick the checkboxes below according to what do you want me (not) to support.
For the sake of completeness I wrote down "everything theoretically possible" and unticked everything that doesn't make sense – but feel free to correct me.

## Expressions (in cases like columns this would only makes sense for `?` SQL params as they aren't escaped by default)

* SELECT
  * [x] columns
  * [ ] FROM
  * [x] JOIN (condition)
  * [x] WHERE
  * [x] GROUP BY
  * [x] HAVING
  * [x] ORDER BY
  * [ ] LIMIT
  * [ ] OFFSET
* INSERT
  * [x] values
* UPDATE
  * [x] values
  * [x] WHERE
* DELETE
  * [x] WHERE

## Scalar subqueries (or subqueries as table)

* SELECT
  * [x] columns
  * [x] FROM (subquery as table)
  * [x] JOIN (subquery as table)
  * [x] WHERE
  * [x] GROUP BY
  * [x] HAVING
  * [x] ORDER BY
  * [ ] LIMIT
  * [ ] OFFSET
* INSERT
  * [x] values
* UPDATE
  * [x] values
  * [x] WHERE
* DELETE
  * [x] WHERE

**Comment by Thomas-Gelf** [comment]
Hint: in addition to the above, depending on your DBMS it is perfectly legal to have JOINs and/or CTEs in UPDATE/DELETE queries. LIMIT and ORDER might also be used on them.

**Comment by Al2Klimov** [comment]
1. CTEs are (always) covered implicitly
2. *If* we'd support JOIN/LIMIT/OFFSET in UPDATE/DELETE, (IMO) we'd equip them w/ exactly the same capabilities as in SELECT

**Comment by lippserd** [comment]
Hi Alex,

I unticked supporting expressions for LIMIT and OFFSET. Everything else absolutely makes sense to support. Do we support something like the following?

    $select = new Select();
    
    $selectForHaving = new Select();
    $otherSelectForHaving = new Select();

    $select->having(['? > ?' => [$selectForHaving, $otherSelectForHaving]]);

**Comment by Al2Klimov** [comment]
1. s/unticked supporting expressions/unticked supporting subqueries/ ?
2. Yes, [I think so](https://github.com/Icinga/ipl/blob/2a2e3d6ca19e78a11c3faf6d6577b1d9180ee4d8/lib/ipl/Sql/QueryBuilder.php#L232)

**Comment by lippserd** [comment]
Supporting subqueries AND expressions for LIMIT and OFFSET is not necessary.

**Comment by Al2Klimov** [comment]
Hello *SQL injection via pagination*! :-)

**Comment by Al2Klimov** [comment]
As discussed offline: no, we cast those to ints implicitly.
